# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/php:7.2-fpm-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update package repository
          command: sudo apt-get update --allow-releaseinfo-change
      - run:
         name: Install PHP libzip-dev
         command: sudo apt-get install -y libzip-dev libpng-dev
      - run:
         name: Install PHP Modules
         command: sudo docker-php-ext-install zip gd

      # not working on composer 2.0
      # - run: sudo composer self-update

      # use composer 1
      - run: sudo composer self-update --1

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "composer.json" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
      - run: composer clearcache
      - run: php -d memory_limit=4096M /usr/local/bin/composer update

#      - save_cache:
#          paths:
#          - ./vendor
#          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: composer unit

workflows:
  version: 2
  build_and_test:
    jobs:
    - build:
        context: Willow
